# Generated by Django 3.0.5 on 2021-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210625_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_marks',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
