# Generated by Django 3.0.5 on 2021-06-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210626_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer4',
        ),
    ]
