# Generated by Django 3.0.5 on 2021-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20210626_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)]),
        ),
    ]
