# Generated by Django 3.0.5 on 2021-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20210626_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
    ]
